version: '3'
services:
  web:
    container_name: web
    image: jcro15/masiviantest
    environment:
      - REDIS_HOST
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: redis:latest
    container_name: db
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379
volumes:
  redisdata: